version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: probot
    versions:
    - 11.1.1
    - 11.2.1
  - dependency-name: fp-ts
    versions:
    - 2.10.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.41
