version: 2
jobs:
  build:
    docker:
      - image: cchantep/golang:1.13-vips # See go-junit-report
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: Prepare working directories
          command: mkdir -p $TEST_RESULTS

      - run:
          name: Check code style
          command: test `gofmt -s -l . | wc -l` -eq 0

      - run:
          name: Build
          command: go build

      - run:
          name: Run tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
